### ISSUE TITLE
`cx env-vars set` doest accept equal sign `=` in the environment value

### ISSUE THREAD

**Issue by babakgh** [cloud66/cx#53]
e.g: `cx env-vars set -s "bgh-test-stack" TEST_VAR=value1=value2`

It should support escaping equal

**Comment by babakgh** [comment]
none of below works
```
TEST_VAR='abcd=efghi'
TEST_VAR="abcd\=efghi"
```

**Comment by iamjohnford** [comment]
The reason I ran into this issue was setting an environment variable to a base64 value. I narrowed it down to the equal sign being the culprit.

**Comment by iamjohnford** [comment]
I'm not familiar with Go but it looks like this might be the line causing the issue:
https://github.com/cloud66/cx/blob/59c538290591295ef91e285023f0600a55647f50/env-vars-set.go#L21

Would it be better to use [flag](https://golang.org/pkg/flag/) to parse args instead of splitting the string?

**Comment by khash** [comment]
@iamjohnford thanks for pointing this out. It was indeed the right line however we use an underlying library for cli parsing which doesn't escape the parameters as expected. Nevertheless it's now fixed in cx 0.1.51 and released. @babakgh will get back to your ticket just to make sure everything is fine.

**Comment by iamjohnford** [comment]
Worked for me. Thanks!
